### ISSUE TITLE
Bug: <TextField /> doesn't accept maxLenght attribute

### ISSUE THREAD

**Issue by eduardogc** [natura-cosmeticos/natds-js#1211]
### Checklist

- [x] I have checked the examples demonstrated at [Storybook](https://natds-js.netlify.app);
- [x] I remembered to add the `<Provider>` for my components to be stylized according to the Storybook;
- [x] I checked the [TROUBLESHOOTING.md](https://github.com/natura-cosmeticos/natds-js/blob/main/TROUBLESHOOTING.md#troubleshooting) file and found that my error is not covered there;
- [x] I've used this Design System before;
- [x] I've used [Material UI](https://material-ui.com/) before.

### Your project dependencies

- `react` version at `package.json` (if included): 16.12.0
- `react-dom` version at `package.json` (if included): 16.12.0
- `@material-ui/core` version at `package.json` (if included directly): 4.10.1

#### Design System libraries

- `@natura-cosmeticos/natds-js` version at `package.json: 1.0.0-alpha.3
- `@natura-cosmeticos/natds-icons` version at `package.json` (if included directly): not applicable
- `@natura-cosmeticos/natds-styles` version at `package.json` (if included directly): not applicable

### Languages & tooling

- What language are you using (like JavaScript, TypeScript) for development? TypeScript
- Are you using `npm` or `yarn` to run and build the application? npm
- Is your project ejected, using `create-react-app` (CRA), `single-spa` or another toolchain? single-spa
- Are your project using some component test library, like Enzyme, React Testing Library? RTL

## Steps to reproduce the behavior

1. Install the package in the version above
2. Do the required setup to load the project
3. Simply try to use TextField as:

```jsx
<TextField maxLength={6} />
```
4. See an exception on the console.

### Do you find this error when you run...

- [ ] `npm install` or `yarn`
- [x] `npm start` or `yarn start`
- [x] `npm run build` or `yarn build`
- [ ] `npm test` or `yarn test`

## Expected behavior

TextField should accept all the default jsx attributes of an input and work correctly.

## Screenshots

Not applicable.
## Additional context

I am using this version of the project because it is a newer compatible version with microfrontend

**Comment by yasminnvaz** [comment]
@eduardogc Thank you for sharing this issue with us.

We add to this component the attribute to `max-length`. Please, let us know if you have any problems using
