### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by LuisHansen** [natura-cosmeticos/natds-js#1241]
**Is your feature request related to a problem? Please describe.**
There's no Select component.

**Describe the solution you'd like**
A styled Select component.

**Describe alternatives you've considered**
Material UI default Select.

**Comment by yasminnvaz** [comment]
Olá!
O componente `Select` foi adicionado a biblioteca na versão 1.4.0 e já está disponível no [NPM](https://www.npmjs.com/package/@naturacosmeticos/natds-web)
