### ISSUE TITLE
Allow Cross-Origin requests to storybook

### ISSUE THREAD

**Issue by lauralucca** [natura-cosmeticos/natds-js#1244]
### Is your feature request related to a problem? Please describe.
Today we can't display inside our design portal _(natds.zeroheight.com)_ the documentation published in the storybook page _(storybook-web.natura.com.br)_ because of blocked access to cross-origin requests.

### Describe the solution you'd like
I'd like to use the already published documentation from Storybook inside our ZeroHeight portal, linking both of them through the embedding of the stories.

### Describe alternatives you've considered
According to the _ZeroHeight_ [Troubleshooting FAQ](https://help.zeroheight.com/3xlwst8/p/507ba7-storybook), we need to unset our `X-Frame-Options` header, in our server configurations, to not send a value for it.

### Additional context
- The error displayed in the browser console when I try to embed the storybook page inside Zero Height:

<img src="https://user-images.githubusercontent.com/30187869/101422608-d48afc80-38d5-11eb-8c09-9133e972e7d4.png" width="550">

- The _ZeroHeight_ Troubleshooting FAQ
https://help.zeroheight.com/3xlwst8/p/507ba7-storybook

**Comment by Design-System-Natura** [comment]
this is a storybook issue, we could try reporting the bug in its repo
