### ISSUE TITLE
Bug: full lodash package import could be optimized for web components

### ISSUE THREAD

**Issue by leonardofalk** [natura-cosmeticos/natds-js#1373]
**Is your feature request related to a problem? Please describe.**
Hello fellow devs!

As the title says, the web package is using lodash, but only for `_.isEqual` method (so far) in [this file](https://github.com/natura-cosmeticos/natds-js/blob/main/packages/web/src/hooks/useDefaultTheme/index.ts)

**Describe the solution you'd like**
I'd like for the package not to include the whole lodash package

**Describe alternatives you've considered**
As for now I'm using an extra babel/webpack step in the project build where I use [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) to remove unused lodash stuff.

Before
![image](https://user-images.githubusercontent.com/5649915/117366548-4bcdb800-ae97-11eb-8af2-65a950c40e95.png)

After
![image](https://user-images.githubusercontent.com/5649915/117367128-1fff0200-ae98-11eb-83e4-75cb4950a6f4.png)

I think the same could be achieved using rollup's plugin: https://www.npmjs.com/package/@optimize-lodash/rollup-plugin

**Comment by yasminnvaz** [comment]
Thank you for this issue! 
We decided to refactor the method that used this dependency and remove it.
