### ISSUE TITLE
An improvement to the select component

### ISSUE THREAD

**Issue by LKTK** [natura-cosmeticos/natds-js#1475]
**Is your feature request related to a problem? Please describe.**
Currently the options array only accepts string or number, this means we cannot show a user friendly option message because it'll become the value of the input. 

**Describe the solution you'd like**
The Select component should behave as a normal html select tag, where the option have the text shown to the user and it's value. 

**Describe alternatives you've considered**
Change the options array to accept an object like so:
{value:1, label: "The label shown in the input"}

**Comment by mprandot** [comment]
The select interface also doesn't accept the principal props (like name, onBlur, etc..).
Would be great if adds those item's too.
