### ISSUE TITLE
Add support for prop "component" in Typography component

### ISSUE THREAD

**Issue by jimmyandrade** [natura-cosmeticos/natds-js#161]
# User story
**Como** uma pessoa desenvolvedora que está utilizando o Design System
**Gostaria de** definir qual tag será renderizada pelo componente Typography
**De forma que** o componente respeite o _outline_ e a semântica da página

# Como reproduzir esta issue
Ao escrever este código:

```jsx
import Typography from "@naturacosmeticos/natds-web/src/Components/Typography"

export default () => (
   <Typography component="h2" variant="h6">Benefícios</Typography>
);
```

# Resultado esperado
Eu esperava que o seguinte código fosse gerado:

```html
<h2 class="MuiTypography-root MuiTypography-h6">Benefícios</h6>
```

# Resultado atual
Mas o componente está gerando o seguinte código:
```html
<h6 class="MuiTypography-root MuiTypography-h6">Benefícios</h6>
```

# Contexto e sugestões

## Contexto de código
https://github.com/natura-cosmeticos/natds-js/blob/eb09f7c0d87afd0058afb63307ab6bc7ef70c9ea/packages/web/src/Components/Typography.tsx#L56-L79

## Sugestões
- Adicionar a chave `component` na `interface ITypographyProps`;
- No retorno do componente, alterar para:

```jsx
return (
    <MaterialTypography
      variant={variant}
      align={align}
      classes={classes}
      color={color}
      noWrap={noWrap}
      component={component}
    >
      {props.children}
    </MaterialTypography>
  );
```

**Comment by robertLichtnow** [comment]
I'll add this feature into the milestone 0.2.0 and create a PR for it.

**Comment by robertLichtnow** [comment]
@jimmyandrade Check the PR and see if it corresponds to the expectations of this issue. Added a few more props and forwarded any other props to the inner component.

**Comment by jimmyandrade** [comment]
I just did code review at #164 and everything seems right to me. But it seems that there is a code conflict at https://github.com/natura-cosmeticos/natds-js/pull/164/files#diff-85fd0b9323046c68226001279f301fa9

**Comment by robertLichtnow** [comment]
PR #164 was merged.
