### ISSUE TITLE
Can't resolve './Themes' in @naturacosmeticos/natds-web

### ISSUE THREAD

**Issue by jimmyandrade** [natura-cosmeticos/natds-js#163]
# User story

**Como** uma pessoa desenvolvedora que está utilizando o Design System
**Gostaria de** poder importar e utilizar os themes
**De forma que** eu possa aplicar os temas visuais da Natura em meu produto

# Como reproduzir esta issue
Ao escrever o seguinte trecho de código:

```jsx
import React from "react"
import {Provider, themes} from "@naturacosmeticos/natds-web"
const {natura} = themes

export default ({children}) => (
  <Provider theme={natura.light}>{children}</Provider>
)
```

# Resultado esperado
Eu rodar `gatsby develop` eu esperava que minha aplicação iria rodar normalmente, e que a seguinte mensagem iria aparecer:

```shell
success run queries - 0.038s - 2/2 51.99/s
```

# Resultado atual
Mas, ao rodar `gatsby develop`, recebo a seguinte mensagem:

```shell

 ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve './Components/Typography' in '~/GitHub/natura/landingpage/node_modules/@naturacosmeticos/natds-web/dist'

File: node_modules/@naturacosmeticos/natds-web/dist/index.js


 ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve './Provider' in '~/GitHub/natura/landingpage/node_modules/@naturacosmeticos/natds-web/dist'

File: node_modules/@naturacosmeticos/natds-web/dist/index.js


 ERROR #98123  WEBPACK

Generating SSR bundle failed

Can't resolve './Themes' in '~/GitHub/natura/landingpage/node_modules/@naturacosmeticos/natds-web/dist'

File: node_modules/@naturacosmeticos/natds-web/dist/index.js
```

**Comment by robertLichtnow** [comment]
Could you provide a minimun prototype where I could reproduce this error?

**Comment by jimmyandrade** [comment]
@robertLichtnow what exactly would this prototype be?

**Comment by robertLichtnow** [comment]
I've closed this issue due to it already being fixed, you can check the PR. For future purposes, I need to reproduce the error, so providing an empty project where this error occurs would help fixing it.

**Comment by jimmyandrade** [comment]
Got it. After updating to v0.1.2, it is now working. Thank you!
