### ISSUE TITLE
TextField label shows "undefined" when property "label" is not set

### ISSUE THREAD

**Issue by jimmyandrade** [natura-cosmeticos/natds-js#172]
I am using `TextField` component to create a field where the prospect can enter their Brazilian CPF. The UX team has designed the prospecting form so that the label doesn't show, but - to avoid accessibility issues - I put the `aria-label` property on input, so screen readers keep reading the label properly.

The problem is that by not entering the `label` property in the component [but setting `required` property as `true`] it shows the text `undefined`. I know I could use CSS to hide the label, but I believe this component should behave the same as what is in the Material UI in this regard.

## To Reproduce
**Given that** I have a component written like this:

```jsx
import TextField from "@naturacosmeticos/natds-web/dist/Components/TextField"

// some code...

<TextField
   inputProps={{"aria-label": "CPF"}}
   placeholder="Informe seu CPF"
   required="true"
   type="text" />
```

### Expected behavior
**When** I do not set the "label"
**And** I set property `required` as `true`
**Then** I expected that the component should be rendered like this:

![screenshot of a text field](https://user-images.githubusercontent.com/2307245/70567655-212de180-1b75-11ea-9f57-5305621ea45f.png)

### Actual screenshot
**But** the component is currently rendering like this:
![screenshot of a text field with undefined label](https://user-images.githubusercontent.com/2307245/70567916-9bf6fc80-1b75-11ea-884b-2b79b50695ea.png)

### Desktop
 - OS: macOS Versão 10.15.1 (Compilação 19B88)
 - Browser: Google Chrome
 - Version: 80.0.3983.2 (Versão oficial) dev 64 bits

### Related code

https://github.com/natura-cosmeticos/natds-js/blob/master/packages/web/src/Components/TextField/index.tsx#L15-L35

**Comment by robertLichtnow** [comment]
This issue as fixed on PR #173 as a hotfix. It is present on version 0.1.3
