### ISSUE TITLE
TabItem is not exported

### ISSUE THREAD

**Issue by nathaliaspinula** [natura-cosmeticos/natds-js#1735]
Hello,

I was trying to use Tab component with TabItem component but the component was not being found. I looked at the source code and 
I've noticed that TabItem component is not being exported in index.js file.

After change the code adding the exportation of the component my application build successfully.

I'm using "@naturacosmeticos/natds-react": "^2.38.0" , node 18.12.0 and React 18.2.0.

**Comment by vagnerbarbosant** [comment]
Thanks for the feedback, we will put the import in the index and in the next release this will be fixed.

**Comment by vagnerbarbosant** [comment]
It was fixed in release 2.39.1 +
