### ISSUE TITLE
Font color doesn't change inside some components

### ISSUE THREAD

**Issue by nathaliaspinula** [natura-cosmeticos/natds-js#1736]
Hi, I'm trying to use dark mode but in some components the font color doesn't change. 

Here is an example of code:

`<Card>
   <Typography variant="subtitle2" color="secondary">Titulo</Typography>
   <Typography variant="overline">Descrição</Typography>
</Card>`

![image](https://user-images.githubusercontent.com/47337136/215612441-ea3cb6a7-2058-4208-93c2-4cbff8c40f3f.png)

I also tried using dark mode with the Drawer and MenuItem, but I had the same problem.

![image](https://user-images.githubusercontent.com/47337136/215612760-5f216e56-5dcf-4460-8de3-aef9c7b4436a.png)

Node version: 18.12.1
"react": "^18.2.0",
"@naturacosmeticos/natds-react": "^2.38.0",

**Comment by vagnerbarbosant** [comment]
Thanks for the feedback, it was fixed in release 2.39.2

**Comment by vagnerbarbosant** [comment]
The card component example in the storybook link can help solve this, see that in the examples the className prop can be used to infer color inheritance in typography.
Link, https://natds-web.natura.design/react/index.html?path=/docs/components-card--playground

![image](https://user-images.githubusercontent.com/119683789/216313885-86c46045-655b-48f6-8995-ea3e4a6f9812.png)
