### ISSUE TITLE
Button doesn't get color applied

### ISSUE THREAD

**Issue by paulononaka** [natura-cosmeticos/natds-js#188]
Hello. We're trying to use the Button component and seems that it isn't applying the theme:

Our code:
```jsx
<Button onClick={subscribe} color="primary" variant="outlined">CLIQUE AQUI PARA SE CADASTRAR</Button>
```

Output:
```html
<button class="MuiButtonBase-root MuiButton-root MuiButton-outlined MuiButton-outlinedPrimary" tabindex="0" type="button" theme="[object Object]">
  <span class="MuiButton-label">CLIQUE AQUI PARA SE CADASTRAR</span>
  <span class="MuiTouchRipple-root"></span>
</button>
```
Note the `[object Object]` on theme attribute.

We noticed that when we were trying to apply the primary color (also the default color) and it isn't getting applied. Is this because of the problem?

Thank you very much.

**Comment by vagnersaraiva** [comment]
Hi @paulononaka,

To use themes, you need to include your components with Provider, e.g.:

```
import { Button, Provider, themes } from '@naturacosmeticos/natds-web';
...
<Provider theme={themes.natura.light}>
  <Button color="primary" variant="outlined">CLIQUE AQUI PARA SE CADASTRAR</Button>
</Provider>
```

**Comment by paulononaka** [comment]
@vagnersaraiva didn't work.

Check this out:

![Screen Shot 2019-12-17 at 15 22 20](https://user-images.githubusercontent.com/449081/71023253-1927f180-20e1-11ea-9920-1eca6946a73f.png)

![Screen Shot 2019-12-17 at 15 22 33](https://user-images.githubusercontent.com/449081/71023255-1b8a4b80-20e1-11ea-8b65-42fa2eedd5ef.png)

@naturacosmeticos/natds-web version "0.1.3"

Am I still loosing something? Thank you.

**Comment by vagnersaraiva** [comment]
Hi @paulononaka,

As it is using variant `outlined` the button looks just like this. You probably want to use variant `contained` as described in the [documentation](https://natds-js.netlify.com/releases/v0.1.3/?path=/docs/web-button--interactive):

![image](https://user-images.githubusercontent.com/4295902/71028128-73c64b00-20eb-11ea-94a1-8b76e838ee32.png)

![image](https://user-images.githubusercontent.com/4295902/71028168-8ccefc00-20eb-11ea-9f05-f0f4a87dfb6e.png)

**Comment by paulononaka** [comment]
My bad! It is working now. Thanks! @vagnersaraiva
