### ISSUE TITLE
Module build error on natds-icons

### ISSUE THREAD

**Issue by eduardogc** [natura-cosmeticos/natds-js#340]
**Describe the bug**
I installed the the module above and when I try to start it, it gives me the error:

```javascript
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError
(1:1) Unknown word
> 1 | var api = require("!../../../style-loader/dist/runtime/injectStylesIntoStyleTag.js");
```

**To Reproduce**
1. Install the package on the latest version
2. Execute it.

**Expected behavior**
It does not throw any error or warning.

**Screenshots**

## Environment

- Are you using `npm` or `yarn` to run and build the application? <ins>npm</ins>;
- What is `react` dependency version? `16.12.0`;
- What is `react-dom` dependency version? `16.12.0`;
- What is `@natura-cosmeticos/natds-js` (Design System) version? `0.6.1`;
- What is `@material-ui/core` version at `package.json` (if included)? `4.10.1`;
- Which component test library does the project use? [e.g. Enzyme, React Testing Library]: `@testing-library/react` `9.4.0` e `@testing-library/jest-dom`: `5.5.0`;
- Is your project ejected, using `create-react-app` (CRA) or another toolchain? `single-spa`;

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Additional context**

**Comment by jimmyandrade** [comment]
@eduardogc pode tentar reproduzir este problema usando a versão `0.19.1` por favor?

**Comment by arielwb** [comment]
Closed due to inactivity.

The package natds-icons has been moved to [this repo](https://github.com/natura-cosmeticos/natds-commons/tree/master/packages/natds-icons).

If the issue still persists, please open a new issue there ;)
