### ISSUE TITLE
Better docs for setup

### ISSUE THREAD

**Issue by eduardogc** [natura-cosmeticos/natds-js#341]
**Is your feature request related to a problem? Please describe.**
I tried to used Natura Design System and noticed that I have to install 3 packages instead of one, standalone package. It complains about the lack of the other packages when I do it.

**Describe the solution you'd like**
Better documentation for setup here in Github and in npm explaining that user has to install 3 packages to work.

**Describe alternatives you've considered**
Alternatively, the packages could work separately, without warning.

**Comment by jimmyandrade** [comment]
Closed by #349

@eduardogc please upgrade to `0.6.5`:
https://www.npmjs.com/package/@naturacosmeticos/natds-web/v/0.6.5
