### ISSUE TITLE
Module not found error: Can't resolve '@material-ui/core/styles'

### ISSUE THREAD

**Issue by eduardogc** [natura-cosmeticos/natds-js#342]
### Do you find this error when you run...

- `npm start` or `yarn`? [Yes|No]
- `npm run build` or `yarn build`? [Yes|No]
- `npm test` or `yarn test`? [Yes|No]

## Environment

- Are you using `npm` or `yarn` to run and build the application? [npm|yarn];
- What is `react` dependency version? [e.g. 16.13.1];
- What is `react-dom` dependency version? [e.g. 16.13.1];
- What is `@natura-cosmeticos/natds-js` (Design System) version? [e.g. 0.4.1];
- What is `@material-ui/core` version at `package.json` (if included)? [e.g. 4.10.0];
- Which component test library does the project use? [e.g. Enzyme, React Testing Library];
- Is your project ejected, using `create-react-app` (CRA) or another toolchain? [Ejected|CRA|Other];

**Comment by jimmyandrade** [comment]
@eduardogc pode tentar reproduzir este problema com a versão `0.19.1`, por favor?

**Comment by arielwb** [comment]
Closed due to inactivity.

If the error still persists, please, open a new issue ;)
