### ISSUE TITLE
Warning: natds-web requires a peer dependency of `react` and `react-dom`

### ISSUE THREAD

**Issue by eduardogc** [natura-cosmeticos/natds-js#345]
## Steps to reproduce the behavior

Use `npm` to start a React project.

Install the following dependencies in the project:

* react@16.12.0
* react-dom@16.12.0
* natura-cosmeticos / natds-js @ 0.6.1
* material-ui / core @ 4.10.1
* testing-library / react @ 9.4.0
* testing-library / jest-dom @ 5.5.0
* single-spa

## Current behavior

```shell script
npm WARN @naturacosmeticos/natds-web@0.6.1 requires a peer of react@16.10.2 but none is installed. You must install peer dependencies yourself.
npm WARN @naturacosmeticos/natds-web@0.6.1 requires a peer of react-dom@16.10.2 but none is installed. You must install peer dependencies yourself.
```

## Expected behavior

There should be no warnings from peer dependencies.

## Environment

- Are you using `npm` or `yarn` to run and build the application? <ins>npm</ins>;
- What is `react` dependency version? `16.12.0`;
- What is `react-dom` dependency version? `16.12.0`;
- What is `@natura-cosmeticos/natds-js` (Design System) version? `0.6.1`;
- What is `@material-ui/core` version at `package.json` (if included)? `4.10.1`;
- Which component test library does the project use? [e.g. Enzyme, React Testing Library]: `@testing-library/react` `9.4.0` e `@testing-library/jest-dom`: `5.5.0`;
- Is your project ejected, using `create-react-app` (CRA) or another toolchain? `single-spa`.

**Comment by jimmyandrade** [comment]
Closed by #352

@eduardogc please upgrade to `v0.6.4` to avoid these warnings:
https://www.npmjs.com/package/@naturacosmeticos/natds-web/v/0.6.4
