### ISSUE TITLE
Using theme provided by natds-styles throws an error

### ISSUE THREAD

**Issue by eduardogc** [natura-cosmeticos/natds-js#348]
## Describe the bug
I tried to use `@natura-cosmeticos/natds-styles` package alongside `@material-ui/core` for styling buttons, but it throws me an error and did not make possible to use it. We use TypeScript on the single-spa app.

## Steps to reproduce the behavior

1. install @material-ui/core
2. install @natura-cosmeticos/natds-styles
3. Use the ThemeProvider like below:
```jsx
import React from "react";
import { themes } from "@naturacosmeticos/natds-styles"
import { ThemeProvider } from '@material-ui/core/styles';
import Button from '@material-ui/core/Button'

export default function Root(props) {
  const { natura } = themes;

  return (
    <ThemeProvider theme={natura.light}>
      <Button color="primary" variant="contained">
        PREVIOUS
      </Button>
      <Button color="secondary" variant="contained">
        NEXT
      </Button>
    </ThemeProvider>
  )
}
```
4. See error:
```javascript
index.js:1 TypeError: Cannot read property 'create' of undefined
    at styles (Button.js:19)
```

### Do you find this error when you run...

- `npm start` or `yarn`? No
- `npm run build` or `yarn build`? Yes
- `npm test` or `yarn test`? Yes

## Expected behavior
Do not throw an error and render theme correctly.

## Environment

- Are you using `npm` or `yarn` to run and build the application? npm
- What is `react` dependency version? 16.12.0;
- What is `react-dom` dependency version? 16.12.0;
- What is `@natura-cosmeticos/natds-js` (Design System) version? 0.6.1;
- What is `@material-ui/core` version at `package.json` (if included)? 4.10.1;
- Which component test library does the project use? React Testing Library;
- Is your project ejected, using `create-react-app` (CRA) or another toolchain? single-spa;

**Comment by arielwb** [comment]
Oi @eduardogc , obrigada pela issue!

O pacote de estilos foi pensado para ser usado junto to natds-web. No natds-web, abstraímos algumas coisas que são necessárias para usar o pacote de estilos com material-ui.
Se você não vai usar o natds-web, você deve seguir a documentação de temas no material (que é o que o provider do natds-web faz)
https://material-ui.com/customization/theming/
Faltou o `createMuiTheme`.

Acho que vale também ver o doc do ThemeProvider e dos High Order Components
https://material-ui.com/styles/api/#themeprovider

:)

**Comment by eduardogc** [comment]
Oi @arielwb, muito obrigado pela resposta!

Segui a orientação e tentei utilizar desta forma, porém o tema que tentei usar deu problema com a interface ThemeOptions mesmo assim.

**Comment by jimmyandrade** [comment]
@eduardogc pode tentar novamente com a versão `0.19.1` da nossa biblioteca, por favor? Obrigade :)

**Comment by arielwb** [comment]
Closed by inactivity.

If anyone else stumble here, we have a sample repo with natds-web used ith single spa and typescript [here](https://github.com/natura-cosmeticos/natds-js-samples)
