### ISSUE TITLE
Bug: expansion panel does not apply colored border when expanding

### ISSUE THREAD

**Issue by joao-vieira** [natura-cosmeticos/natds-js#507]
### Related dependencies

- `react` version at `package.json` (if included): **"^16.12.0"**
- `react-dom` version at `package.json` (if included): **"^16.12.0"**
- `@material-ui/core` version at `package.json` (if included): -

### Design System libraries

- `@natura-cosmeticos/natds-js` version at `package.json` (if included): **"^0.7.15"**
- `@natura-cosmeticos/natds-icons` version at `package.json` (if included): -
- `@natura-cosmeticos/natds-styles` version at `package.json` (if included): -

### Languages & tooling

- What language are you using (like JavaScript, TypeScript) for development? **JavaScript**
- Are you using `npm` or `yarn` to run and build the application? **yarn**
- Is your project ejected, using `create-react-app` (CRA), `single-spa` or another toolchain? **We use create-react-app (CRA)**
- Which component test library (Enzyme, React Testing Library) does the project use? **Exactly the three mentioned as an example**

## Describe the bug
Despite including and using the simplest example demonstrated at [natds-js.netlify.app](https://natds-js.netlify.app/releases/v0.6.13/?path=/story/components-expansionpanel--interactive), the expansion panel does not have a colored border when expanding on the screen.

## Steps to reproduce the behavior

1. Import the DS: `yarn add @naturacosmeticos/natds-web`
2. Include the simplest example provided [here](https://natds-js.netlify.app/releases/v0.6.13/?path=/story/components-expansionpanel--interactive) (the first, with `subtitle1` and `outlined-navigation-arrowbottom icon` only)
3. Click on expansion panel
4. See error (expansion panel without border)

### Do you find this error when you run...

- `npm start` or `yarn`? [**Yes**]
- `npm run build` or `yarn build`? [**No**]
- `npm test` or `yarn test`? [**No**]

## Expected behavior
The expansion panel is expected to look exactly like the demo example.

### Closed expansion panels

![ExpansionPanels Closed](https://user-images.githubusercontent.com/28982977/86141516-88d35c00-bac8-11ea-9fe7-e1b18df243b1.png)

### Expanded expansion panels

![ExpansionPanels Expanded](https://user-images.githubusercontent.com/28982977/86141533-8c66e300-bac8-11ea-8111-dec688c7c8fe.png)

## Additional context
This is the first component I use with this design system (although I have already used [material-ui](https://material-ui.com/)). Please, if I have made a mistake or missing information, let me know.

Thanks for your work. Regards.

**Comment by jimmyandrade** [comment]
@joao-vieira 

Thank you very much for the very detailed issue. I'm sorry for the delay in answering you.
Just checking, are you using the `<Provider>` component of our Design System to ensure that styling is being done?

**Comment by joao-vieira** [comment]
Hello! Thanks for your answer :)

Unfortunately, I did not use the `Provider` component. I simply imported the `ExpansionPanel` and used it on my page. Do I just need to import `Provider` and use it around the `ExpansionPanel`?

Predicting future cases, will I need to involve all components of the design system with the provider or is the best practice to place it somewhere more "general" in the application?

**Comment by jimmyandrade** [comment]
@joao-vieira Hello! Sorry again for the delay.

Yes, you'll always need to import `Provider` but instead of using it only around ExpansionPanel, it would be better if you wrap all your application with `Provider`. For example: inside an `App/index.js` file:

https://github.com/natura-cosmeticos/natds-js-examples/blob/ce3c04778b0d023934d8dfbea8d577fe9355c92a/examples/react/src/App/index.js#L1-L11

**Comment by joao-vieira** [comment]
Right, thank you!

**Comment by jimmyandrade** [comment]
@joao-vieira 

I saw that you closed the issue. Is it everything working now? 😄

**Comment by joao-vieira** [comment]
@jimmyandrade 

Yes, I followed your instructions and read the new section on troubleshooting (which actually looks really cool).
I'm glad I made a minimal contribution to a new use case 😃

**Comment by jimmyandrade** [comment]
@joao-vieira Thank you for that!

Questions like yours help us to always improve the documentation. Sometimes small contributions in terms of code make a big difference. Thank you for using and contributing to the Design System 😄
