### ISSUE TITLE
fix: TextField with type `date` is being rendered as a resizable textarea

### ISSUE THREAD

**Issue by jimmyandrade** [natura-cosmeticos/natds-js#657]
### Checklist

- [ ] I have checked the examples demonstrated at [Storybook](https://natds-js.netlify.app);
- [ ] I remembered to add the `<Provider>` for my components to be stylized according to the Storybook;
- [ ] I checked the [TROUBLESHOOTING.md](https://github.com/natura-cosmeticos/natds-js/blob/master/TROUBLESHOOTING.md#troubleshooting) file and found that my error is not covered there;
- [ ] I've used this Design System before;
- [ ] I've used [Material UI](https://material-ui.com/) before.

### Your project dependencies

- `react` version at `package.json` (if included):
- `react-dom` version at `package.json` (if included):
- `@material-ui/core` version at `package.json` (if included directly):

#### Design System libraries

- `@natura-cosmeticos/natds-js` version at `package.json:
- `@natura-cosmeticos/natds-icons` version at `package.json` (if included directly):
- `@natura-cosmeticos/natds-styles` version at `package.json` (if included directly):

### Languages & tooling

- What language are you using (like JavaScript, TypeScript) for development?
- Are you using `npm` or `yarn` to run and build the application?
- Is your project ejected, using `create-react-app` (CRA), `single-spa` or another toolchain?
- Are your project using some component test library, like Enzyme, React Testing Library?

## Steps to reproduce the behavior

1. Import...
2. Include...
3. Click on...
4. Find error...

### Do you find this error when you run...

- [ ] `npm install` or `yarn`
- [ ] `npm start` or `yarn start`
- [ ] `npm run build` or `yarn build`
- [ ] `npm test` or `yarn test`

## Screenshots

![image](https://user-images.githubusercontent.com/2307245/87972135-c9f1d700-ca9c-11ea-8251-d663f2178454.png)

**Comment by yasminnvaz** [comment]
I was looking for this problem and realised that it doesn't happen anymore so I will close this issue

![Screen Shot 2020-12-16 at 09 46 06](https://user-images.githubusercontent.com/42593623/102350472-bc754600-3f83-11eb-98a3-8929ddf631b2.png)
