### ISSUE TITLE
Bug: textfield (type password) shows 2 eye icons on edge

### ISSUE THREAD

**Issue by mathvaleriano** [natura-cosmeticos/natds-js#804]
### Checklist

- [x] I have checked the examples demonstrated at [Storybook](https://natds-js.netlify.app);
- [x] I remembered to add the `<Provider>` for my components to be stylized according to the Storybook;
- [x] I checked the [TROUBLESHOOTING.md](https://github.com/natura-cosmeticos/natds-js/blob/main/TROUBLESHOOTING.md#troubleshooting) file and found that my error is not covered there;
- [x] I've used this Design System before;
- [x] I've used [Material UI](https://material-ui.com/) before.

### Your project dependencies

- `react` version at `package.json` (if included):^16.13.1
- `react-dom` version at `package.json` (if included):^16.13.1
- `@material-ui/core` version at `package.json` (if included directly):

#### Design System libraries

- `@natura-cosmeticos/natds-js` version at `package.json:^0.16.11
- `@natura-cosmeticos/natds-icons` version at `package.json` (if included directly):
- `@natura-cosmeticos/natds-styles` version at `package.json` (if included directly):

### Languages & tooling

- What language are you using (like JavaScript, TypeScript) for development? Javascript
- Are you using `npm` or `yarn` to run and build the application? yarn
- Is your project ejected, using `create-react-app` (CRA), `single-spa` or another toolchain? Just using CRA, but it has not been
- Are your project using some component test library, like Enzyme, React Testing Library? No

## Steps to reproduce the behavior

1. on microsoft edge
2. open styleguide or project and go to some page that contains a textfield of password type
3. type something
4. clear this field using backspace
5. type again

### Do you find this error when you run...

- [ ] `npm install` or `yarn`
- [ ] `npm start` or `yarn start`
- [ ] `npm run build` or `yarn build`
- [ ] `npm test` or `yarn test`

## Expected behavior

It should show only one icon, ignoring the default icon of the browser

## Screenshots

![image](https://user-images.githubusercontent.com/12265496/90054001-a0018e00-dcb1-11ea-9407-19f7ee3732c0.png)

**Comment by bimlendu33** [comment]
Hello All,
Any updates on this.? I am also facing same in React with Material UI app.

**Comment by IsraelOzuna** [comment]
Currently I'm using Material UI v5 and the problem continues. The only way that I found was hide it with CSS

In the index.html paste the following lines

<style>
      input::-ms-reveal,
      input::-ms-clear {
        display: none;
      }
</style>

I hope that helps
